from datetime import datetime

chat_history = []

def get_greeting():
    current_hour = datetime.now().hour
    if current_hour < 12:
        return "Good morning! ☀️"
    elif 12 <= current_hour < 18:
        return "Good afternoon! 🌤️"
    else:
        return "Good evening! 🌙"

def show_help():
    return """\nThings you can ask my_chat_bot:
- Say hello, hi, hey
- Ask 'how are you?'
- Ask 'what's your name?'
- Ask 'what can you do?'
- Ask about 'weather'
- Say 'i am bored'
- Ask for a joke: 'tell me a joke'
- Ask 'what is python?'
- Say 'thank you'
- Ask 'what is the time?'
- Say 'open google'
- Type 'history' to view past messages
- Type 'bye' or 'exit' to quit
"""
def my_chat_bot_response(user_input):
    user_input = user_input.lower().strip()
    timestamp = datetime.now().strftime("[%H:%M:%S]")

    if user_input == "history":
        if not chat_history:
            response = "my_chat_bot: No messages yet!"
        else:
            response = "\n".join(chat_history)
        return response, False

    chat_history.append(f"You: {user_input} {timestamp}")

    name = "Raghavi Priya"

    if any(word in user_input for word in ["hello", "hi", "hey"]):
        greeting = get_greeting()
        response = f"my_chat_bot: Hi {name}. {greeting} How can I help you today?"

    elif "how are you" in user_input:
        response = "my_chat_bot: I’m running smoothly! How about you? 😊"

    elif "your name" in user_input or "who are you" in user_input:
        response = "my_chat_bot: I’m my_chat_bot, your friendly terminal-based assistant."

    elif "what can you do" in user_input or "help" == user_input:
        response = "my_chat_bot: Here's what I can do:\n" + show_help()

    elif "weather" in user_input:
        response = "my_chat_bot: The forecast says 100% chance of chatting with me. ☁️"

    elif "joke" in user_input:
        response = "my_chat_bot: Why don't programmers like nature? Too many bugs! 😂"

    elif "time" in user_input:
        response = f"my_chat_bot: It's currently {datetime.now().strftime('%I:%M %p')}."

    elif "who created you" in user_input:
        response = "my_chat_bot: I was manually written by a human, not generated by AI!"

    elif "i am bored" in user_input:
        response = "my_chat_bot: Try reading a book, taking a walk, or... chatting with me more! 😉"

    elif "thank you" in user_input:
        response = "my_chat_bot: You're welcome! I'm always here for a chat. 🤗"

    elif "good night" in user_input:
        response = "my_chat_bot: Sweet dreams! 🌙💤"

    elif "good morning" in user_input:
        response = "my_chat_bot: Morning sunshine! ☀️ Hope you have a great day."

    elif "what is python" in user_input:
        response = "my_chat_bot: Python is a powerful programming language used for web, data science, automation, and more!"

    elif "open google" in user_input:
        response = "my_chat_bot: I can't open websites, but you can visit https://www.google.com anytime!"

    elif user_input in ["bye", "exit", "quit"]:
        confirm = input("my_chat_bot: Are you sure you want to exit? (yes/no): ").strip().lower()
        if confirm == "yes":
            response = "my_chat_bot: Bye! It was lovely chatting with you. 👋"
            chat_history.append(f"{response} {timestamp}")
            return response, True
        else:
            response = "my_chat_bot: Great! Let's continue. 😄"

    else:
        response = "my_chat_bot: Hmm... I didn't understand that. Try typing 'help' to see what I know."

    chat_history.append(f"{response} {timestamp}")
    return response, False
    
def start_chat():
    print("\n💬 Welcome to my_chat_bot!")
    print("Type anything to begin. Type 'help' for options.\n")

    while True:
        user_input = input("You: ")
        response, should_exit = my_chat_bot_response(user_input)
        print(response)
        if should_exit:
            break

if __name__ == "__main__":
    start_chat()
